---
- name: Install base OS dependencies
  ansible.builtin.apt:
    name:
      - fail2ban
      - nano
      - wget
      - ca-certificates
      - openssl
      - ntpsec
      - git
      - unzip
    state: present
    install_recommends: false
    update_cache: true
